name: Compile

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'lib/**'
      - 'platformio.ini'

jobs:
  compile_firmware:
    name: Compile the firmware
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Compile hub75 firmware
        run: pio run --environment hub75

      - name: Upload hub75 firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hub75_firmware
          path: .pio/build/hub75/firmware.bin
